"""Add organization_id to trusted_registry

Revision ID: cf1d9f96d150
Revises: 20250128_0001_multi_tenant
Create Date: 2026-01-29 00:29:28.629997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1d9f96d150'
down_revision: Union[str, None] = '20250128_0001_multi_tenant'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add user_id to alerts as NULLABLE first (existing rows have no user)
    op.add_column('alerts', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Step 2: Set existing alerts to user_id=1 (admin user)
    op.execute("UPDATE alerts SET user_id = 1 WHERE user_id IS NULL")
    
    # Step 3: Now make it NOT NULL
    op.alter_column('alerts', 'user_id', existing_type=sa.INTEGER(), nullable=False)
    
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'alerts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'alerts', 'users', ['acknowledged_by'], ['id'])
    op.create_foreign_key(None, 'alerts', 'email_analyses', ['email_analysis_id'], ['id'])
    
    # Fix email_analyses: set NULL user_ids to admin first
    op.execute("UPDATE email_analyses SET user_id = 1 WHERE user_id IS NULL")
    op.alter_column('email_analyses', 'user_id', existing_type=sa.INTEGER(), nullable=False)
    
    # Handle index recreation safely
    try:
        op.drop_index('ix_email_analyses_message_id', table_name='email_analyses')
    except Exception:
        pass  # Index may not exist
    op.create_index(op.f('ix_email_analyses_message_id'), 'email_analyses', ['message_id'], unique=False)
    op.create_index(op.f('ix_email_analyses_mail_account_id'), 'email_analyses', ['mail_account_id'], unique=False)
    op.create_foreign_key(None, 'email_analyses', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'phishing_reports', 'users', ['reporter_id'], ['id'])
    op.create_foreign_key(None, 'phishing_reports', 'users', ['investigated_by'], ['id'])
    
    # Add organization_id columns (nullable is fine)
    op.add_column('threat_alerts', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_threat_alerts_organization_id'), 'threat_alerts', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'threat_alerts', 'organizations', ['organization_id'], ['id'])
    
    op.add_column('trusted_registry', sa.Column('organization_id', sa.Integer(), nullable=True))
    try:
        op.drop_index('ix_trusted_registry_email_address', table_name='trusted_registry')
    except Exception:
        pass
    op.create_index(op.f('ix_trusted_registry_email_address'), 'trusted_registry', ['email_address'], unique=False)
    op.create_index(op.f('ix_trusted_registry_organization_id'), 'trusted_registry', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'trusted_registry', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'trusted_registry', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'trusted_registry', 'users', ['added_by'], ['id'])
    
    # Remove legacy organization column from users (nullable, safe to drop)
    try:
        op.drop_column('users', 'organization')
    except Exception:
        pass  # Column may not exist


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trusted_registry', type_='foreignkey')
    op.drop_constraint(None, 'trusted_registry', type_='foreignkey')
    op.drop_constraint(None, 'trusted_registry', type_='foreignkey')
    op.drop_index(op.f('ix_trusted_registry_organization_id'), table_name='trusted_registry')
    op.drop_index(op.f('ix_trusted_registry_email_address'), table_name='trusted_registry')
    op.create_index('ix_trusted_registry_email_address', 'trusted_registry', ['email_address'], unique=False)
    op.drop_column('trusted_registry', 'organization_id')
    op.drop_constraint(None, 'threat_alerts', type_='foreignkey')
    op.drop_index(op.f('ix_threat_alerts_organization_id'), table_name='threat_alerts')
    op.drop_column('threat_alerts', 'organization_id')
    op.drop_constraint(None, 'phishing_reports', type_='foreignkey')
    op.drop_constraint(None, 'phishing_reports', type_='foreignkey')
    op.drop_constraint(None, 'email_analyses', type_='foreignkey')
    op.drop_index(op.f('ix_email_analyses_mail_account_id'), table_name='email_analyses')
    op.drop_index(op.f('ix_email_analyses_message_id'), table_name='email_analyses')
    op.create_index('ix_email_analyses_message_id', 'email_analyses', ['message_id'], unique=False)
    op.alter_column('email_analyses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_column('alerts', 'user_id')
    # ### end Alembic commands ###
